sudo: false
dist: trusty
language: php
cache:
  directories:
    - $HOME/.composer/cache
php:
  - nightly
  - 7.4
  - 7.3
  - 7.2
  - 7.1
install:
  - composer self-update
  - composer install --prefer-dist
script:
  - make lint
  - make test
