sudo: false
dist: trusty
language: php
cache:
  directories:
    - $HOME/.composer/cache
php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6
install:
  - composer self-update
  - composer install --prefer-dist
script:
  - make test
